# Generated by Django 3.1.1 on 2020-09-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200909_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharma',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
